version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tickets-it-app
    container_name: tickets_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html                # Mapear el proyecto local al contenedor
      - ./storage:/var/www/html/storage # Persistencia en storage
    networks:
      - tickets_network
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: tickets_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: tickets_it_app  # Nombre de la base de datos sincronizado
      MYSQL_USER: ticketsuser
      MYSQL_PASSWORD: secretpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql          # Persistencia para los datos de la DB
    networks:
      - tickets_network

  web:
    image: nginx:alpine
    container_name: tickets_web
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html                # Mapear el proyecto local
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - tickets_network

volumes:
  dbdata:

networks:
  tickets_network:
